import React from "react";
import { Link } from "react-router-dom";

const PrivacyPolicy = () => {
  return (
    <div className="bg-gray-100 p-8 text-gray-800">
      <div className="max-w-4xl mx-auto bg-white shadow-lg rounded-lg p-6">
        <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
        <p className="text-sm text-gray-600 mb-6">Last updated: October 30, 2024</p>
        <p className="mb-6">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
          information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p className="mb-6">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
          collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created
          with the help of the{" "}
          <Link
            to="https://www.termsfeed.com/privacy-policy-generator/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-500 hover:underline"
          >
            Privacy Policy Generator
          </Link>
          .
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>
        
        <h3 className="text-xl font-semibold mt-6 mb-2">Interpretation</h3>
        <p className="mb-6">
          The words of which the initial letter is capitalized have meanings defined under the following conditions.
          The following definitions shall have the same meaning regardless of whether they appear in singular or in
          plural.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        
        <ul className="list-disc list-inside space-y-4 pl-4 mt-4">
          <li>
            <strong>Account</strong> means a unique account created for You to access our Service or parts of our
            Service.
          </li>
          <li>
            <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a
            party, where "control" means ownership of 50% or more of the shares, equity interest or other securities
            entitled to vote for election of directors or other managing authority.
          </li>
          <li>
            <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)
            refers to Winsum Planet.
          </li>
          <li>
            <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device
            by a website, containing the details of Your browsing history on that website among its many uses.
          </li>
          <li>
            <strong>Country</strong> refers to: Jharkhand, India
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a
            digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the
            Company.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
            Service or from the Service infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>Website</strong> refers to Winsum Planet, accessible from{" "}
            <Link
              to="https://www.winsumplanet.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-blue-500 hover:underline"
            >
              https://www.winsumplanet.com
            </Link>
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal
            entity on behalf of which such individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Collecting and Using Your Personal Data</h2>

        <h3 className="text-xl font-semibold mt-6 mb-2">Types of Data Collected</h3>

        <h4 className="text-lg font-semibold mt-4 mb-2">Personal Data</h4>
        <p className="mb-6">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that
          can be used to contact or identify You. Personally identifiable information may include, but is not limited
          to:
        </p>
        
        <ul className="list-disc list-inside space-y-4 pl-4">
          <li>Usage Data</li>
        </ul>

        <h4 className="text-lg font-semibold mt-4 mb-2">Usage Data</h4>
        <p className="mb-6">
          Usage Data is collected automatically when using the Service. Usage Data may include information such as Your
          Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service
          that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and
          other diagnostic data.
        </p>

        <h4 className="text-lg font-semibold mt-4 mb-2">Tracking Technologies and Cookies</h4>
        <p className="mb-6">
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
          information.
        </p>

        <ul className="list-disc list-inside space-y-4 pl-4">
          <li>
            <strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can
            instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do
            not accept Cookies, You may not be able to use some parts of our Service.
          </li>
          <li>
            <strong>Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic
            files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs).
          </li>
        </ul>

        <p className="mt-6">
          For more information about the cookies we use and your choices regarding cookies, please visit our Cookies
          Policy or the Cookies section of our Privacy Policy.
        </p>

        <h3 className="text-xl font-semibold mt-8 mb-4">Use of Your Personal Data</h3>
        <p>
          The Company may use Personal Data for the following purposes:
        </p>

        <ul className="list-disc list-inside space-y-4 pl-4 mt-4">
          <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
          <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
          <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
        </ul>

        <p className="mt-6">
          We may share Your personal information in the following situations:
        </p>
        
        <ul className="list-disc list-inside space-y-4 pl-4 mt-4">
          <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service.</li>
          <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
        </ul>

        <h3 className="text-xl font-semibold mt-8 mb-4">Retention of Your Personal Data</h3>
        <p>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this
          Privacy Policy.
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
